# Generated by Django 2.2.16 on 2020-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20201112_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/%Y%m', verbose_name='封面图'),
        ),
    ]
